import { PacketType } from './packet-type';
import { Packet } from './packet';

import * as IncomingPackets from './packets/incoming';
import * as OutgoingPackets from './packets/outgoing';

/**
 * A factory which constructs a new packet instance.
 */
type PacketFactory = () => Packet;

/**
 * Maps each packet type to a factory for the matching packet class.
 */
const PACKET_FACTORIES: { [key in PacketType]?: PacketFactory } = {
  [PacketType.FAILURE]: () => new IncomingPackets.FailurePacket(),
  [PacketType.ACCEPT_ARENA_DEATH]: () => new OutgoingPackets.AcceptArenaDeathPacket(),
  [PacketType.LOAD]: () => new OutgoingPackets.LoadPacket(),
  [PacketType.QUEST_REDEEM_RESPONSE]: () => new IncomingPackets.QuestRedeemResponsePacket(),
  [PacketType.TRADEACCEPTED]: () => new IncomingPackets.TradeAcceptedPacket(),
  [PacketType.GOTOACK]: () => new OutgoingPackets.GotoAckPacket(),
  [PacketType.PET_CHANGE_FORM_MSG]: () => new OutgoingPackets.ReskinPetPacket(),
  [PacketType.GUILDREMOVE]: () => new OutgoingPackets.GuildRemovePacket(),
  [PacketType.TRADEDONE]: () => new IncomingPackets.TradeDonePacket(),
  [PacketType.HELLO]: () => new OutgoingPackets.HelloPacket(),
  [PacketType.MOVE]: () => new OutgoingPackets.MovePacket(),
  [PacketType.CHATTOKEN]: () => new IncomingPackets.ChatToken(),
  [PacketType.CHATHELLO]: () => new OutgoingPackets.ChatHelloPacket(),
  [PacketType.SETCONDITION]: () => new OutgoingPackets.SetConditionPacket(),
  [PacketType.ACTIVEPETUPDATE]: () => new IncomingPackets.ActivePetPacket(),
  [PacketType.PONG]: () => new OutgoingPackets.PongPacket(),
  [PacketType.CANCELTRADE]: () => new OutgoingPackets.CancelTradePacket(),
  [PacketType.OTHERHIT]: () => new OutgoingPackets.OtherHitPacket(),
  [PacketType.IMMINENT_ARENA_WAVE]: () => new IncomingPackets.ImminentArenaWavePacket(),
  [PacketType.GLOBAL_NOTIFICATION]: () => new IncomingPackets.GlobalNotificationPacket(),
  [PacketType.TRADECHANGED]: () => new IncomingPackets.TradeChangedPacket(),
  [PacketType.PETYARDUPDATE]: () => new IncomingPackets.PetYardUpdate(),
  [PacketType.DAMAGE]: () => new IncomingPackets.DamagePacket(),
  [PacketType.CREATE_SUCCESS]: () => new IncomingPackets.CreateSuccessPacket(),
  [PacketType.QUEST_FETCH_ASK]: () => new OutgoingPackets.QuestFetchAskPacket(),
  [PacketType.TELEPORT]: () => new OutgoingPackets.TeleportPacket(),
  [PacketType.EVOLVE_PET]: () => new IncomingPackets.EvolvedPetMessage(),
  [PacketType.UPDATEACK]: () => new OutgoingPackets.UpdateAckPacket(),
  [PacketType.UPDATE]: () => new IncomingPackets.UpdatePacket(),
  [PacketType.INVITEDTOGUILD]: () => new IncomingPackets.InvitedToGuildPacket(),
  [PacketType.USEITEM]: () => new OutgoingPackets.UseItemPacket(),
  [PacketType.TRADESTART]: () => new IncomingPackets.TradeStartPacket(),
  [PacketType.CLAIM_LOGIN_REWARD_MSG]: () => new OutgoingPackets.ClaimDailyRewardMessage(),
  [PacketType.SHOWEFFECT]: () => new IncomingPackets.ShowEffectPacket(),
  [PacketType.DEATH]: () => new IncomingPackets.DeathPacket(),
  [PacketType.RESKIN]: () => new OutgoingPackets.ReskinPacket(),
  [PacketType.RETITLE]: () => new OutgoingPackets.RetitlePacket(),
  [PacketType.CLAIM_CHEST_REWARD]: () => new OutgoingPackets.ClaimChestRewardPacket(),
  [PacketType.CHEST_REWARD_RESULT]: () => new IncomingPackets.ChestRewardResultPacket(),
  [PacketType.PLAYERTEXT]: () => new OutgoingPackets.PlayerTextPacket(),
  [PacketType.DELETE_PET]: () => new IncomingPackets.DeletePetMessage(),
  [PacketType.QUEST_REDEEM]: () => new OutgoingPackets.QuestRedeemPacket(),
  [PacketType.USEPORTAL]: () => new OutgoingPackets.UsePortalPacket(),
  [PacketType.KEY_INFO_RESPONSE]: () => new IncomingPackets.KeyInfoResponsePacket(),
  [PacketType.ACCEPTTRADE]: () => new OutgoingPackets.AcceptTradePacket(),
  [PacketType.RECONNECT]: () => new IncomingPackets.ReconnectPacket(),
  [PacketType.BUYRESULT]: () => new IncomingPackets.BuyResultPacket(),
  [PacketType.REQUESTTRADE]: () => new OutgoingPackets.RequestTradePacket(),
  [PacketType.PETUPGRADEREQUEST]: () => new OutgoingPackets.PetUpgradeRequestPacket(),
  [PacketType.SHOOTACK]: () => new OutgoingPackets.ShootAckPacket(),
  [PacketType.PLAYERHIT]: () => new OutgoingPackets.PlayerHitPacket(),
  [PacketType.ACTIVE_PET_UPDATE_REQUEST]: () => new OutgoingPackets.ActivePetUpdateRequestPacket(),
  [PacketType.PLAYSOUND]: () => new IncomingPackets.PlaySoundPacket(),
  [PacketType.PLAYERSHOOT]: () => new OutgoingPackets.PlayerShootPacket(),
  [PacketType.ESCAPE]: () => new OutgoingPackets.EscapePacket(),
  [PacketType.GUILDRESULT]: () => new IncomingPackets.GuildResultPacket(),
  [PacketType.NOTIFICATION]: () => new IncomingPackets.NotificationPacket(),
  [PacketType.VERIFY_EMAIL]: () => new IncomingPackets.VerifyEmailPacket(),
  [PacketType.GOTO]: () => new IncomingPackets.GotoPacket(),
  [PacketType.MAPINFO]: () => new IncomingPackets.MapInfoPacket(),
  [PacketType.INVDROP]: () => new OutgoingPackets.InvDropPacket(),
  [PacketType.ARENA_DEATH]: () => new IncomingPackets.ArenaDeathPacket(),
  [PacketType.ALLYSHOOT]: () => new IncomingPackets.AllyShootPacket(),
  [PacketType.SERVERPLAYERSHOOT]: () => new IncomingPackets.ServerPlayerShootPacket(),
  [PacketType.PASSWORD_PROMPT]: () => new IncomingPackets.PasswordPromptPacket(),
  [PacketType.FILE]: () => new IncomingPackets.FilePacket(),
  [PacketType.KEY_INFO_REQUEST]: () => new OutgoingPackets.KeyInfoRequestPacket(),
  [PacketType.QUEST_ROOM_MSG]: () => new OutgoingPackets.GoToQuestRoomPacket(),
  [PacketType.CHECKCREDITS]: () => new OutgoingPackets.CheckCreditsPacket(),
  [PacketType.ENEMYHIT]: () => new OutgoingPackets.EnemyHitPacket(),
  [PacketType.CREATE]: () => new OutgoingPackets.CreatePacket(),
  [PacketType.GUILDINVITE]: () => new OutgoingPackets.GuildInvitePacket(),
  [PacketType.ENTER_ARENA]: () => new OutgoingPackets.EnterArenaPacket(),
  [PacketType.PING]: () => new IncomingPackets.PingPacket(),
  [PacketType.EDITACCOUNTLIST]: () => new OutgoingPackets.EditAccountListPacket(),
  [PacketType.AOE]: () => new IncomingPackets.AoePacket(),
  [PacketType.ACCOUNTLIST]: () => new IncomingPackets.AccountListPacket(),
  [PacketType.BUY]: () => new OutgoingPackets.BuyPacket(),
  [PacketType.INVSWAP]: () => new OutgoingPackets.InvSwapPacket(),
  [PacketType.AOEACK]: () => new OutgoingPackets.AoeAckPacket(),
  [PacketType.PIC]: () => new IncomingPackets.PicPacket(),
  [PacketType.INVRESULT]: () => new IncomingPackets.InvResultPacket(),
  [PacketType.LOGIN_REWARD_MSG]: () => new IncomingPackets.ClaimDailyRewardResponse(),
  [PacketType.CHANGETRADE]: () => new OutgoingPackets.ChangeTradePacket(),
  [PacketType.TEXT]: () => new IncomingPackets.TextPacket(),
  [PacketType.QUESTOBJID]: () => new IncomingPackets.QuestObjectIdPacket(),
  [PacketType.QUEST_FETCH_RESPONSE]: () => new IncomingPackets.QuestFetchResponsePacket(),
  [PacketType.TRADEREQUESTED]: () => new IncomingPackets.TradeRequestedPacket(),
  [PacketType.HATCH_PET]: () => new IncomingPackets.HatchPetMessage(),
  [PacketType.GROUNDDAMAGE]: () => new OutgoingPackets.GroundDamagePacket(),
  [PacketType.ENEMYSHOOT]: () => new IncomingPackets.EnemyShootPacket(),
  [PacketType.CHOOSENAME]: () => new OutgoingPackets.ChooseNamePacket(),
  [PacketType.CLIENTSTAT]: () => new IncomingPackets.ClientStatPacket(),
  [PacketType.RESKIN_UNLOCK]: () => new IncomingPackets.ReskinUnlockPacket(),
  [PacketType.NAMERESULT]: () => new IncomingPackets.NameResultPacket(),
  [PacketType.JOINGUILD]: () => new OutgoingPackets.JoinGuildPacket(),
  [PacketType.NEWTICK]: () => new IncomingPackets.NewTickPacket(),
  [PacketType.SQUAREHIT]: () => new OutgoingPackets.SquareHitPacket(),
  [PacketType.CHANGEGUILDRANK]: () => new OutgoingPackets.ChangeGuildRankPacket(),
  [PacketType.NEW_ABILITY]: () => new IncomingPackets.NewAbilityMessage(),
  [PacketType.CREATEGUILD]: () => new OutgoingPackets.CreateGuildPacket(),
  [PacketType.PET_CHANGE_SKIN_MSG]: () => new OutgoingPackets.ChangePetSkinPacket(),
  [PacketType.REALM_HERO_LEFT_MSG]: () => new IncomingPackets.RealmHeroesLeftPacket(),
  [PacketType.RESET_DAILY_QUESTS]: () => new OutgoingPackets.ResetDailyQuestsPacket(),
  [PacketType.NEW_CHARACTER_INFORMATION]: () => new IncomingPackets.NewCharacterInfoPacket(),
  [PacketType.QUEUE_INFORMATION]: () => new IncomingPackets.QueueInfoPacket(),
  [PacketType.QUEUE_CANCEL]: () => new OutgoingPackets.QueueCancelPacket(),
  [PacketType.VAULT_CONTENT]: () => new IncomingPackets.VaultContentPacket(),
  [PacketType.EXALTATION_BONUS_CHANGED]: () => new IncomingPackets.ExaltationUpdatePacket(),
  [PacketType.FORGE_UNLOCKED_BLUEPRINTS]: () => new IncomingPackets.ForgeUnlockedBlueprints(),
  [PacketType.PROGRESS_UPDATE]: () => new IncomingPackets.ProgressUpdatePacket(),
  [PacketType.FORGE_REQUEST]: () => new OutgoingPackets.ForgeRequestPacket(),
  [PacketType.FORGE_RESULT]: () => new IncomingPackets.ForgeResultPacket(),
  [PacketType.CHANGE_ALLY_SHOOT]: () => new OutgoingPackets.ChangeAllyShootPacket(),
  [PacketType.CONVERT_SEASONAL_CHARACTER]: () => new OutgoingPackets.ConvertSeasonalCharacterPacket(),
  [PacketType.GET_PLAYERS_LIST_MESSAGE]: () => new OutgoingPackets.GetPlayersListPacket(),
  [PacketType.MODERATOR_ACTION_MESSAGE]: () => new OutgoingPackets.ModeratorActionMessagePacket(),
  [PacketType.CREEP_MOVE_MESSAGE]: () => new OutgoingPackets.CreepMoveMessagePacket(),
  [PacketType.PLAYER_CALLOUT]: () => new OutgoingPackets.PlayerCalloutPacket(),
  [PacketType.DASH]: () => new OutgoingPackets.DashPacket(),
  [PacketType.DASH_ACK]: () => new OutgoingPackets.DashAckPacket(),
  [PacketType.FAVOUR_PET]: () => new OutgoingPackets.FavourPetPacket(),
  [PacketType.REALM_SCORE_UPDATE]: () => new IncomingPackets.RealmScoreUpdatePacket(),
  [PacketType.CRUCIBLE_REQUEST]: () => new OutgoingPackets.CrucibleRequestPacket(),
  [PacketType.CRUCIBLE_RESPONSE]: () => new IncomingPackets.CrucibleResponsePacket(),
  [PacketType.BLACKSMITH_REQUEST]: () => new OutgoingPackets.BlacksmithRequestPacket(),
  [PacketType.BLACKSMITH_DISMANTLE]: () => new IncomingPackets.BlacksmithDismantlePacket(),
  [PacketType.REROLL_ALL_ENCHANTMENTS]: () => new OutgoingPackets.RerollAllEnchantmentsPacket(),
  [PacketType.ENCHANT]: () => new IncomingPackets.EnchantPacket(),
  [PacketType.RESET_ENCHANTMENT_REROLL_COUNT]: () => new OutgoingPackets.ResetEnchantmentRerollCountPacket(),
  [PacketType.RESET_ENCHANTMENT_REROLL_COUNT_RESULT]: () => new IncomingPackets.ResetEnchantmentRerollCountResultPacket(),
  [PacketType.CLAIM_DAILY_ITEM]: () => new IncomingPackets.ClaimDailyItemPacket(),
  [PacketType.SELECT_ENTRANCE]: () => new OutgoingPackets.SelectEntrancePacket(),
  [PacketType.BUY_EMOTE]: () => new OutgoingPackets.BuyEmotePacket(),
  [PacketType.UNKNOWN224]: () => new OutgoingPackets.Unknown224Packet(),
  [PacketType.CLAIM_MISSION]: () => new OutgoingPackets.ClaimMissionPacket(),
  [PacketType.CLAIM_MISSION_RESULT]: () => new IncomingPackets.ClaimMissionResultPacket(),
  [PacketType.STATS]: () => new IncomingPackets.StatsPacket(),
  [PacketType.EMOTE]: () => new OutgoingPackets.EmotePacket(),
  [PacketType.CLAIM_REWARDS_INFO_PROMPT]: () => new IncomingPackets.ClaimRewardsInfoPromptPacket(),
  [PacketType.REDEEM_VOUCHER]: () => new OutgoingPackets.RedeemVoucherPacket(),
  [PacketType.VOUCHER_RESULT]: () => new IncomingPackets.VoucherResultPacket(),
  [PacketType.CLAIM_ACCOUNT_LEVEL_REWARD]: () => new OutgoingPackets.ClaimAccountLevelRewardPacket(),
  [PacketType.CLAIM_ACCOUNT_LEVEL_REWARD_RESULT]: () => new IncomingPackets.ClaimAccountLevelRewardResultPacket(),
  [PacketType.CLAIM_REWARD]: () => new OutgoingPackets.ClaimRewardPacket(),
  [PacketType.CLAIM_REWARD_RESULT]: () => new IncomingPackets.ClaimRewardResultPacket(),
  [PacketType.CLAIM_REWARDS_INFO_REQUEST]: () => new OutgoingPackets.ClaimRewardsInfoRequestPacket(),
};

/**
 * Creates the correct packet object for the given type.
 * @param type The type of packet to create
 * @throws {Error} if the packet cannot be created
 */
export function createPacket(type: PacketType): Packet {
  if (typeof type !== 'string') {
    throw new TypeError(`Parameter "type" must be a string, not ${typeof type}`);
  }
  const factory = PACKET_FACTORIES[type];
  if (!factory) {
    throw new Error(`Unknown packet type: ${type}`);
  }
  return factory();
}
