name: CI

on:
  push:
  pull_request:

jobs:
  library:
    name: realmlib (lib)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: typecheck
        run: npx tsc -p . --noEmit
      - name: test
        run: npm test
